// Abzeichen-Katalog für Server-Meldungen (Audit-Runde 2, 25.09.2026).
//
// Kopie von id, Emoji, Name und Beschreibung aus src/lib/badges.ts (ALL_BADGES,
// bei doppelter id gilt der erste Eintrag). api/ importiert nichts aus src/
// (liegt außerhalb von tsconfig und Vite-Aliassen), darum diese Kopie.
// /api/send-notification nimmt den Text der Telegram-Meldung NUR von hier —
// vorher kamen Name und Beschreibung ungeprüft aus dem Browser.
// Neue Abzeichen hier nachtragen; fehlt eine id, geht ein allgemeiner Text raus.

/** id → [Emoji, Name, Beschreibung] */
export const ABZEICHEN: Readonly<Record<string, readonly [string, string, string]>> = {
  "first_infusion": ["🌱", "Frischling", "Dein erster Aufguss — der Anfang von etwas Großem."],
  "infusion_5": ["🔥", "Heizer", "5 Aufgüsse — du weißt wie man einheitzt."],
  "infusion_10": ["💧", "Wasserkünstler", "10 Aufgüsse — Dampf und Wasser gehorchen dir."],
  "infusion_20": ["🌿", "Kräutermeister", "20 Aufgüsse — die Aromen tanzen nach deiner Pfeife."],
  "infusion_35": ["⚡", "Energiebündel", "35 Aufgüsse — pure Energie, die die Hitze antreibt."],
  "infusion_50": ["🌊", "Wellenmeister", "50 Aufgüsse — deine Wellen tragen die Wärme durch den ganzen Raum."],
  "infusion_75": ["👑", "Sauna-König", "75 Aufgüsse — du trägst die Krone der Hitze."],
  "infusion_100": ["🏆", "Legende", "100 Aufgüsse — unvergessen, unübertroffen, legendär."],
  "team_3": ["🤝", "Teamplayer", "3 Team-Aufgüsse — gemeinsam ist man stärker."],
  "team_10": ["💫", "Duo-Dynamo", "10 Team-Aufgüsse — ihr brennt zusammen."],
  "team_20": ["🔗", "Synergist", "20 Team-Aufgüsse — eine unschlagbare Einheit."],
  "pioneer": ["⭐", "Pionier", "Einer der ersten 3 Aufgieser des Vereins — du hast den Weg geebnet."],
  "early_bird": ["🌅", "Frühaufsteher", "Ein Aufguss um 11:00 Uhr — der frühe Meister weckt die Sauna."],
  "night_owl": ["🌙", "Nachtschicht", "Ein Aufguss um 20:00 Uhr — der letzte Glut des Abends."],
  "allrounder": ["🎯", "Allrounder", "In jeder aktiven Sauna aufgegossen — kein Ofen zu heiß, kein Raum zu unbekannt."],
  "marathon": ["🏃", "Marathon", "3 Aufgüsse an einem Tag — ausnahmslose Hingabe."],
  "feedback_giver": ["💬", "Feedback-Geber", "10 Bewertungen abgegeben — du hilfst anderen besser zu werden."],
  "streak_4w": ["🔥", "Stammgast", "4 Wochen in Folge mindestens 1× anwesend — du hältst die Glut am Leben."],
  "streak_12w": ["🔥🔥", "Sauna-Pflanze", "12 Wochen in Folge anwesend — du wurzelst hier tief."],
  "streak_24w": ["🔥🔥🔥", "Halbjahres-Marathon", "24 Wochen in Folge anwesend — unermüdlich, unverwüstlich, unverzichtbar."],
  "first_sauna_day": ["🔥", "Erster Sauna-Tag", "Dein erster Tag in der Sauna — willkommen in der Wärme!"],
  "regular_5": ["🌡️", "Stamm-Gast", "5 Sauna-Tage gesammelt — du wirst zum Gewohnheitstier."],
  "regular_15": ["🌡️", "Treuer Gast", "15 Sauna-Tage — die Sauna hat dich fest im Griff."],
  "regular_30": ["🌡️", "Sauna-Veteran", "30 Sauna-Tage — die Schwarzwald-Schwitze ist deine zweite Heimat."],
  "regular_60": ["🏆", "Sauna-Legende", "60 Sauna-Tage — du bist Teil des Inventars."],
  "first_rating": ["⭐", "Erster Eindruck", "Erste Aufguss-Bewertung abgegeben — deine Stimme zählt."],
  "feedback_pro": ["📋", "Bewertungs-Profi", "50 Aufgüsse bewertet — du kennst die feinen Unterschiede."],
  "feedback_top": ["🏆", "Top-Bewerter", "100 Aufgüsse bewertet — eine echte Instanz."],
  "curious": ["🔍", "Neugier", "Aufgüsse von 3 verschiedenen Aufgießern bewertet."],
  "vielsauner": ["🌍", "Vielsauner", "10 verschiedene Aufgießer entdeckt — du suchst die Vielfalt."],
  "connaisseur": ["👑", "Connaisseur", "25 verschiedene Aufgießer kennengelernt — Kenner par excellence."],
  "sauna_allrounder": ["🌐", "Sauna-Allrounder", "Bewertungen in allen 3 Saunen abgegeben — kein Schweiß-Grad zu heiß."],
  "first_fan": ["❤️", "Erster Fan", "Du folgst deinem ersten Aufgießer — der Anfang einer Freundschaft."],
  "collector_5": ["🌟", "Sammler", "5 Aufgießern gefolgt — dein Lieblings-Team wird größer."],
  "collector_15": ["🌟", "Großer Sammler", "15 Aufgießern gefolgt — du hast einen feinen Geschmack."],
  "collector_30": ["💖", "Mega-Fan", "30 Aufgießern gefolgt — du liebst sie wirklich alle."],
  "pioneer_gast": ["🎖️", "Pioneer-Gast", "Unter den ersten 10 registrierten Gästen — du warst von Anfang an dabei."],
  "birthday_visitor": ["🎂", "Geburtstags-Gast", "An deinem Geburtstag in der Sauna gewesen — beste Art zu feiern."],
  "winter_guest": ["❄️", "Wintergast", "10× im Winter (Dez–Feb) in der Sauna — du hasst die Kälte."],
  "summer_guest": ["☀️", "Sommergast", "10× im Sommer (Jun–Aug) in der Sauna — Hitze ist Hitze."],
  "eagle_eye": ["🦅", "Adlerauge", "10 Aufgüsse noch am selben Tag bewertet — du vergisst nichts."],
  "volunteer_first": ["🤝", "Erste Hilfe", "Erste Helfer-Anmeldung — willkommen im Unterstützer-Kreis!"],
  "volunteer_5": ["🤝", "Helfer", "5 Helfer-Einsätze — du bist verlässlich."],
  "volunteer_25": ["🛠️", "Aktivposten", "25 Helfer-Einsätze — ohne dich läuft hier nichts."],
  "volunteer_50": ["🏅", "Vereins-Stütze", "50 Helfer-Einsätze — eine tragende Säule."],
  "volunteer_100": ["💎", "Säulen-Heilige", "100 Helfer-Einsätze — Legenden-Status für Helfer."],
  "event_helper_first": ["🎪", "Event-Premiere", "Bei einem Vereins-Event mitgemacht."],
  "event_helper_5": ["🎭", "Event-Profi", "5 Events mitgestaltet — du machst Stimmung."],
  "event_helper_10": ["🏆", "Event-Held", "10 Events mitorganisiert — Mister/Mrs. Saunafest!"],
  "care_hero_first": ["🌱", "Erste Pflege", "Erste Pflege-Aufgabe übernommen."],
  "care_hero_5": ["🌿", "Pflege-Held", "5 Pflege-Einsätze — du hältst alles am Laufen."],
  "care_hero_15": ["🌳", "Pflege-Meister", "15 Pflege-Einsätze — der Verein dankt!"],
  "early_bird_helper_3": ["⚡", "Schnell-Helfer", "3× innerhalb 1 Stunde nach Veröffentlichung angemeldet."],
  "early_bird_helper_10": ["🌅", "Sofort-Reagierer", "10× innerhalb 1 Stunde nach Veröffentlichung angemeldet — du bist immer da."],
  "games_first_win": ["🥇", "Erster Sieg", "Dein erster Sieg gegen einen anderen Mitspieler."],
  "tetris_king": ["🧱", "Tetris-König", "Tetris-Highscore von mindestens 10 000 erreicht."],
  "tetris_legend": ["👑", "Tetris-Legende", "Tetris-Highscore von mindestens 50 000 — beeindruckend."],
  "chess_master": ["♟️", "Schach-Meister", "10 Schach-Siege — kühlster Kopf am Brett."],
  "chess_grandmaster": ["♛", "Schach-Großmeister", "50 Schach-Siege — Verein zittert vor dir."],
  "g2048_solver": ["2️⃣", "2048-Knacker", "Die 2048-Kachel im Spiel 2048 erreicht."],
};
